sArenaMixin.drList = {
    [207167]  = "Disorient",       -- Blinding Sleet
    [198909]  = "Disorient",       -- Song of Chi-ji
    [202274]  = "Disorient",       -- Incendiary Brew
    [33786]   = "Disorient",       -- Cyclone
    [209753]  = "Disorient",       -- Cyclone Honor Talent
    [31661]   = "Disorient",       -- Dragon's Breath
    [105421]  = "Disorient",       -- Blinding Light
    [8122]    = "Disorient",       -- Psychic Scream
    [605]     = "Disorient",       -- Mind Control
    [2094]    = "Disorient",       -- Blind
    [5782]    = "Disorient",       -- Fear
    [118699]  = "Disorient",       -- Fear (Incorrect?)
    [130616]  = "Disorient",       -- Fear (Incorrect?)
    [5484]    = "Disorient",       -- Howl of Terror
    [115268]  = "Disorient",       -- Mesmerize
    [6358]    = "Disorient",       -- Seduction
    [5246]    = "Disorient",       -- Intimidating Shout
    [207685]  = "Disorient",       -- Sigil of Misery
    [236748]  = "Disorient",       -- Intimidating Roar
    [226943]  = "Disorient",       -- Mind Bomb
    [2637]    = "Disorient",       -- Hibernate

    [99]      = "Incapacitate",    -- Incapacitating Roar
    [203126]  = "Incapacitate",    -- Maim (Blood trauma)
    [236025]  = "Incapacitate",    -- Enraged Maim
    [3355]    = "Incapacitate",    -- Freezing Trap
    [203337]  = "Incapacitate",    -- Freezing Trap (Honor Talent)
    [212365]  = "Incapacitate",    -- Freezing Trap (Incorrect?)
    [19386]   = "Incapacitate",    -- Wyvern Sting
    [209790]  = "Incapacitate",    -- Freezing Arrow
    [213691]  = "Incapacitate",    -- Scatter Shot
    [118]     = "Incapacitate",    -- Polymorph
    [126819]  = "Incapacitate",    -- Polymorph (Porcupine)
    [61721]   = "Incapacitate",    -- Polymorph (Rabbit)
    [28271]   = "Incapacitate",    -- Polymorph (Turtle)
    [28272]   = "Incapacitate",    -- Polymorph (Pig)
    [161353]  = "Incapacitate",    -- Polymorph (Bear cub)
    [161372]  = "Incapacitate",    -- Polymorph (Peacock)
    [61305]   = "Incapacitate",    -- Polymorph (Black Cat)
    [61780]   = "Incapacitate",    -- Polymorph (Turkey)
    [161355]  = "Incapacitate",    -- Polymorph (Penguin)
    [161354]  = "Incapacitate",    -- Polymorph (Monkey)
    [277792]  = "Incapacitate",    -- Polymorph (Bumblebee)
    [277787]  = "Incapacitate",    -- Polymorph (Baby Direhorn)
    [82691]   = "Incapacitate",    -- Ring of Frost
    [115078]  = "Incapacitate",    -- Paralysis
    [20066]   = "Incapacitate",    -- Repentance
    [9484]    = "Incapacitate",    -- Shackle Undead
    [200196]  = "Incapacitate",    -- Holy Word: Chastise
    [1776]    = "Incapacitate",    -- Gouge
    [6770]    = "Incapacitate",    -- Sap
    [199743]  = "Incapacitate",    -- Parley
    [51514]   = "Incapacitate",    -- Hex
    [211004]  = "Incapacitate",    -- Hex (Spider)
    [210873]  = "Incapacitate",    -- Hex (Raptor)
    [211015]  = "Incapacitate",    -- Hex (Cockroach)
    [211010]  = "Incapacitate",    -- Hex (Snake)
    [196942]  = "Incapacitate",    -- Hex (Voodoo Totem)
    [277784]  = "Incapacitate",    -- Hex (Wicker Mongrel)
    [277778]  = "Incapacitate",    -- Hex (Zandalari Tendonripper)
    [710]     = "Incapacitate",    -- Banish
    [6789]    = "Incapacitate",    -- Mortal Coil
    [107079]  = "Incapacitate",    -- Quaking Palm
    [217832]  = "Incapacitate",    -- Imprison
    [221527]  = "Incapacitate",    -- Imprison (Honor Talent)
    [197214]  = "Incapacitate",    -- Sundering

    [47476]   = "Silence",         -- Strangulate
    [204490]  = "Silence",         -- Sigil of Silence
    [78675]   = "Silence",         -- Solar Beam
    [202933]  = "Silence",         -- Spider Sting
    [233022]  = "Silence",         -- Spider Sting 2
    [217824]  = "Silence",         -- Shield of Virtue
    [199683]  = "Silence",         -- Last Word
    [15487]   = "Silence",         -- Silence
    [1330]    = "Silence",         -- Garrote
    [43523]   = "Silence",         -- Unstable Affliction Silence Effect
    [196364]  = "Silence",         -- Unstable Affliction Silence Effect 2

    [210141]  = "Stun",            -- Zombie Explosion
    [108194]  = "Stun",            -- Asphyxiate (unholy)
    [221562]  = "Stun",            -- Asphyxiate (blood)
    [91800]   = "Stun",            -- Gnaw
    [212332]  = "Stun",            -- Smash
    [91797]   = "Stun",            -- Monstrous Blow
    [22570]   = "Stun",            -- Maim (invalid?)
    [203123]  = "Stun",            -- Maim
    [163505]  = "Stun",            -- Rake (Prowl)
    [5211]    = "Stun",            -- Mighty Bash
    [19577]   = "Stun",            -- Intimidation (no longer used?)
    [24394]   = "Stun",            -- Intimidation
    [119381]  = "Stun",            -- Leg Sweep
    [853]     = "Stun",            -- Hammer of Justice
    [1833]    = "Stun",            -- Cheap Shot
    [408]     = "Stun",            -- Kidney Shot
    [199804]  = "Stun",            -- Between the Eyes
    [118905]  = "Stun",            -- Static Charge (Capacitor Totem)
    [118345]  = "Stun",            -- Pulverize
    [89766]   = "Stun",            -- Axe Toss
    [171017]  = "Stun",            -- Meteor Strike (Infernal)
    [171018]  = "Stun",            -- Meteor Strike (Abyssal)
    --	[22703]   = "Stun",            -- Infernal Awakening (doesn't seem to DR)
    [30283]   = "Stun",            -- Shadowfury
    [46968]   = "Stun",            -- Shockwave
    [132168]  = "Stun",            -- Shockwave (Protection)
    [145047]  = "Stun",            -- Shockwave (Proving Grounds PvE)
    [132169]  = "Stun",            -- Storm Bolt
    [64044]   = "Stun",            -- Psychic Horror
    [200200]  = "Stun",            -- Holy Word: Chastise Censure
    --	[204399]  = "Stun",            -- Earthfury (doesn't seem to DR)
    [179057]  = "Stun",            -- Chaos Nova
    [205630]  = "Stun",            -- Illidan's Grasp, primary effect
    [208618]  = "Stun",            -- Illidan's Grasp, secondary effect
    [211881]  = "Stun",            -- Fel Eruption
    [20549]   = "Stun",            -- War Stomp
    [199085]  = "Stun",            -- Warpath
    [204437]  = "Stun",            -- Lightning Lasso
    [255723]  = "Stun",            -- Bull Rush
    [202244]  = "Stun",            -- Overrun
    --	[213688]  = "Stun",            -- Fel Cleave (doesn't seem to DR)
    [202346]  = "Stun",            -- Double Barrel

    [204085]  = "Root",            -- Deathchill
    [233395]  = "Root",            -- Frozen Center
    [339]     = "Root",            -- Entangling Roots
    [170855]  = "Root",            -- Entangling Roots (Nature's Grasp)
    [201589]  = "Root",            -- Entangling Roots (Tree of Life)
    [235963]  = "Root",            -- Entangling Roots (Feral honor talent)
    --	[45334]   = "Root",            -- Immobilized (Wild Charge) FIXME: only DRs with itself
    [102359]  = "Root",            -- Mass Entanglement
    [162480]  = "Root",            -- Steel Trap
    --	[190927]  = "Root",            -- Harpoon FIXME: only DRs with itself
    [200108]  = "Root",            -- Ranger's Net
    [212638]  = "Root",            -- Tracker's net
    [201158]  = "Root",            -- Super Sticky Tar
    [136634]  = "Root",            -- Narrow Escape
    [122]     = "Root",            -- Frost Nova
    [33395]   = "Root",            -- Freeze
    [198121]  = "Root",            -- Frostbite
    [220107]  = "Root",            -- Frostbite (Water Elemental? needs testing)
    [116706]  = "Root",            -- Disable
    [64695]   = "Root",            -- Earthgrab (Totem effect)
    [233582]  = "Root",            -- Entrenched in Flame
    [117526]  = "Root",            -- Binding Shot
    [207171]  = "Root",            -- Winter is Coming

    --[[
    [207777]  = "Disarm",          -- Dismantle
    [233759]  = "Disarm",          -- Grapple Weapon
    [236077]  = "Disarm",          -- Disarm
    [236236]  = "Disarm",          -- Disarm (Prot)
    [209749]  = "Disarm",          -- Faerie Swarm (Balance)
    ]]
}